version: '2'
services:
  jupyter:
    build: .
    container_name: jupyter 
    network_mode: "host"
    ports:
     - "8888:8888"
     - "6006:6006"
    volumes:
     - /home/aaron/jupyter-notebooks:/notebooks
    command: /run_jupyter.sh